import 'package:flutter/material.dart';
import 'package:task_flow/shared/models/workspace.dart';

class CreateWorkspaceForm extends StatefulWidget {
  final Function(Workspace) onCreate;
  final String ownerId;

  const CreateWorkspaceForm({
    super.key,
    required this.onCreate,
    required this.ownerId,
  });

  @override
  State<CreateWorkspaceForm> createState() => _CreateWorkspaceFormState();
}

class _CreateWorkspaceFormState extends State<CreateWorkspaceForm> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  void _submitForm() {
    if (_formKey.currentState!.validate()) {
      final workspace = Workspace(
        id: '', // Will be generated by Firebase
        name: _nameController.text.trim(),
        ownerId: widget.ownerId,
        createdAt: DateTime.now(),
      );
      
      widget.onCreate(workspace);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const Text(
            'Create New Workspace',
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 24),
          TextFormField(
            controller: _nameController,
            decoration: const InputDecoration(
              labelText: 'Workspace Name',
              border: OutlineInputBorder(),
            ),
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Please enter a workspace name';
              }
              if (value.length < 3) {
                return 'Workspace name must be at least 3 characters';
              }
              return null;
            },
          ),
          const SizedBox(height: 24),
          SizedBox(
            width: double.infinity,
            height: 50,
            child: ElevatedButton(
              onPressed: _submitForm,
              child: const Text('Create Workspace'),
            ),
          ),
        ],
      ),
    );
  }
}